<?php

namespace Database\Seeders;

use App\Models\Countries;
use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $count = Countries::withoutGlobalScopes()->get()->count();

        if ($count == 0) {
            echo "Qtde: " . $count . " Populating...";

            Countries::create(['name' => 'Albania', 'country_code' => 'ALB', 'country_num_code' => 8, 'language_code' => 'sq']);
            Countries::create(['name' => 'Algeria', 'country_code' => 'DZA', 'country_num_code' => 12, 'language_code' => 'ar']);
            Countries::create(['name' => 'Andorra', 'country_code' => 'AND', 'country_num_code' => 20, 'language_code' => 'ca']);
            Countries::create(['name' => 'Angola', 'country_code' => 'AGO', 'country_num_code' => 24, 'language_code' => 'pt']);
            Countries::create(['name' => 'Anguilla', 'country_code' => 'AIA', 'country_num_code' =>	660, 'language_code' => 'en']);
            Countries::create(['name' => 'Argentina', 'country_code' => 'ARG', 'country_num_code' => 32, 'language_code' => 'es']);
            Countries::create(['name' => 'Armenia', 'country_code' => 'ARM', 'country_num_code' => 51, 'language_code' => 'hy']);
            Countries::create(['name' => 'Australia', 'country_code' => 'AUS', 'country_num_code' => 36, 'language_code' => 'en']);
            Countries::create(['name' => 'Austria', 'country_code' => 'AUT', 'country_num_code' => 40, 'language_code' => 'de']);
            Countries::create(['name' => 'Azerbaijan', 'country_code' => 'AZE', 'country_num_code' => 31, 'language_code' => 'az']);
            Countries::create(['name' => 'Bahamas', 'country_code' => 'BHS', 'country_num_code' => 44, 'language_code' => 'en']);
            Countries::create(['name' => 'Bahrain', 'country_code' => 'BHR', 'country_num_code' => 48, 'language_code' => 'ar']);
            Countries::create(['name' => 'Bangladesh', 'country_code' => 'BGD', 'country_num_code' => 50, 'language_code' => 'bn']);
            Countries::create(['name' => 'Barbados', 'country_code' => 'BRB', 'country_num_code' => 52, 'language_code' => 'en']);
            Countries::create(['name' => 'Belarus', 'country_code' => 'BLR', 'country_num_code' => 112, 'language_code' => 'be']);
            Countries::create(['name' => 'Belgium', 'country_code' => 'BEL', 'country_num_code' => 56, 'language_code' => 'nl']);
            Countries::create(['name' => 'Belize', 'country_code' => 'BLZ', 'country_num_code' => 84, 'language_code' => 'en']);
            Countries::create(['name' => 'Benin', 'country_code' => 'BEN', 'country_num_code' => 204, 'language_code' => 'fr']);
            Countries::create(['name' => 'Bhutan', 'country_code' => 'BTN', 'country_num_code' => 64, 'language_code' => 'dz']);
            Countries::create(['name' => 'Bolivia', 'country_code' => 'BOL', 'country_num_code' => 68, 'language_code' => 'es']);
            Countries::create(['name' => 'Bosnia and Herzegovina', 'country_code' => 'BIH', 'country_num_code' => 70, 'language_code' => 'bs']);
            Countries::create(['name' => 'Botswana', 'country_code' => 'BWA', 'country_num_code' => 72, 'language_code' => 'en']);
            Countries::create(['name' => 'Brazil', 'country_code' => 'BRA', 'country_num_code' => 76, 'language_code' => 'pt']);
            Countries::create(['name' => 'Brunei Darussalam', 'country_code' => 'BRN', 'country_num_code' => 96, 'language_code' => 'ms']);
            Countries::create(['name' => 'Bulgaria', 'country_code' => 'BGR', 'country_num_code' => 100, 'language_code' => 'bg']);
            Countries::create(['name' => 'Burkina Faso', 'country_code' => 'BFA', 'country_num_code' => 854, 'language_code' => 'fr']);
            Countries::create(['name' => 'Burundi', 'country_code' => 'BDI', 'country_num_code' => 108, 'language_code' => 'fr']);
            Countries::create(['name' => 'Cabo Verde', 'country_code' => 'CPV', 'country_num_code' => 132, 'language_code' => 'pt']);
            Countries::create(['name' => 'Cambodia', 'country_code' => 'KHM', 'country_num_code' => 116, 'language_code' => 'km']);
            Countries::create(['name' => 'Cameroon', 'country_code' => 'CMR', 'country_num_code' => 120, 'language_code' => 'fr']);
            Countries::create(['name' => 'Canada', 'country_code' => 'CAN', 'country_num_code' => 124, 'language_code' => 'en']);
            Countries::create(['name' => 'Central African Republic', 'country_code' => 'CAF', 'country_num_code' => 140, 'language_code' => 'fr']);
            Countries::create(['name' => 'Chad', 'country_code' => 'TCD', 'country_num_code' => 148, 'language_code' => 'fr']);
            Countries::create(['name' => 'Chile', 'country_code' => 'CHL', 'country_num_code' => 152, 'language_code' => 'es']);
            Countries::create(['name' => 'China', 'country_code' => 'CHN', 'country_num_code' => 156, 'language_code' => 'zh-hans']);
            Countries::create(['name' => 'Colombia', 'country_code' => 'COL', 'country_num_code' => 170, 'language_code' => 'es']);
            Countries::create(['name' => 'Comoros', 'country_code' => 'COM', 'country_num_code' => 174, 'language_code' => 'ar']);
            Countries::create(['name' => 'Congo', 'country_code' => 'COG', 'country_num_code' => 178, 'language_code' => 'fr']);
            Countries::create(['name' => 'Costa Rica', 'country_code' => 'CRI', 'country_num_code' => 188, 'language_code' => 'es']);
            Countries::create(['name' => 'Croatia', 'country_code' => 'HRV', 'country_num_code' => 191, 'language_code' => 'hr']);
            Countries::create(['name' => 'Cuba', 'country_code' => 'CUB', 'country_num_code' => 192, 'language_code' => 'es']);
            Countries::create(['name' => 'Cyprus', 'country_code' => 'CYP', 'country_num_code' => 196, 'language_code' => 'el']);
            Countries::create(['name' => 'Czechia', 'country_code' => 'CZE', 'country_num_code' => 203, 'language_code' => 'cs']);
            Countries::create(['name' => 'Côte dIvoire', 'country_code' => 'CIV', 'country_num_code' => 384, 'language_code' => 'fr']);
            Countries::create(['name' => 'Democratic Republic of the Congo', 'country_code' => 'COD', 'country_num_code' => 180, 'language_code' => 'fr']);
            Countries::create(['name' => 'Denmark', 'country_code' => 'DNK', 'country_num_code' => 208, 'language_code' => 'da']);
            Countries::create(['name' => 'Djibouti', 'country_code' => 'DJI', 'country_num_code' => 262, 'language_code' => 'fr']);
            Countries::create(['name' => 'Dominica', 'country_code' => 'DMA', 'country_num_code' => 212, 'language_code' => 'en']);
            Countries::create(['name' => 'Dominican Republic', 'country_code' => 'DOM', 'country_num_code' => 214, 'language_code' => 'es']);
            Countries::create(['name' => 'Ecuador', 'country_code' => 'ECU', 'country_num_code' => 218, 'language_code' => 'es']);
            Countries::create(['name' => 'Egypt', 'country_code' => 'EGY', 'country_num_code' => 818, 'language_code' => 'ar']);
            Countries::create(['name' => 'El Salvador', 'country_code' => 'SLV', 'country_num_code' => 222, 'language_code' => 'es']);
            Countries::create(['name' => 'Equatorial Guinea', 'country_code' => 'GNQ', 'country_num_code' => 226, 'language_code' => 'es']);
            Countries::create(['name' => 'Eritrea', 'country_code' => 'ERI', 'country_num_code' => 232, 'language_code' => 'ti']);
            Countries::create(['name' => 'Estonia', 'country_code' => 'EST', 'country_num_code' => 233, 'language_code' => 'et']);
            Countries::create(['name' => 'Eswatini', 'country_code' => 'SWZ', 'country_num_code' => 748, 'language_code' => 'ss']);
            Countries::create(['name' => 'Ethiopia', 'country_code' => 'ETH', 'country_num_code' => 231, 'language_code' => 'am, om']);
            Countries::create(['name' => 'Fiji', 'country_code' => 'FJI', 'country_num_code' => 242, 'language_code' => 'en']);
            Countries::create(['name' => 'Finland', 'country_code' => 'FIN', 'country_num_code' => 246, 'language_code' => 'fi']);
            Countries::create(['name' => 'France', 'country_code' => 'FRA', 'country_num_code' => 250, 'language_code' => 'fr']);
            Countries::create(['name' => 'Gabon', 'country_code' => 'GAB', 'country_num_code' => 266, 'language_code' => 'fr']);
            Countries::create(['name' => 'Gambia', 'country_code' => 'GMB', 'country_num_code' => 270, 'language_code' => 'en']);
            Countries::create(['name' => 'Georgia', 'country_code' => 'GEO', 'country_num_code' => 268, 'language_code' => 'ka']);
            Countries::create(['name' => 'Germany', 'country_code' => 'DEU', 'country_num_code' => 276, 'language_code' => 'de']);
            Countries::create(['name' => 'Ghana', 'country_code' => 'GHA', 'country_num_code' => 288, 'language_code' => 'en']);
            Countries::create(['name' => 'Greece', 'country_code' => 'GRC', 'country_num_code' => 300, 'language_code' => 'el']);
            Countries::create(['name' => 'Grenada', 'country_code' => 'GRD', 'country_num_code' => 308, 'language_code' => 'en']);
            Countries::create(['name' => 'Guatemala', 'country_code' => 'GTM', 'country_num_code' => 320, 'language_code' => 'es']);
            Countries::create(['name' => 'Guinea', 'country_code' => 'GIN', 'country_num_code' => 324, 'language_code' => 'fr']);
            Countries::create(['name' => 'Guinea-Bissau', 'country_code' => 'GNB', 'country_num_code' => 624, 'language_code' => 'pt']);
            Countries::create(['name' => 'Guyana', 'country_code' => 'GUY', 'country_num_code' => 328, 'language_code' => 'en']);
            Countries::create(['name' => 'Haiti', 'country_code' => 'HTI', 'country_num_code' => 332, 'language_code' => 'fr']);
            Countries::create(['name' => 'Holy See (the) - City of the Vatican', 'country_code' => 'VAT', 'country_num_code' => 336, 'language_code' => 'it']);
            Countries::create(['name' => 'Honduras', 'country_code' => 'HND', 'country_num_code' => 340, 'language_code' => 'es']);
            Countries::create(['name' => 'Hungary', 'country_code' => 'HUN', 'country_num_code' => 348, 'language_code' => 'hu']);
            Countries::create(['name' => 'Iceland', 'country_code' => 'ISL', 'country_num_code' => 352, 'language_code' => 'is']);
            Countries::create(['name' => 'India', 'country_code' => 'IND', 'country_num_code' => 356, 'language_code' => 'hi']);
            Countries::create(['name' => 'Indonesia', 'country_code' => 'IDN', 'country_num_code' => 360, 'language_code' => 'id']);
            Countries::create(['name' => 'Iran', 'country_code' => 'IRN', 'country_num_code' => 364, 'language_code' => 'fa']);
            Countries::create(['name' => 'Iraq', 'country_code' => 'IRQ', 'country_num_code' => 368, 'language_code' => 'ar']);
            Countries::create(['name' => 'Ireland', 'country_code' => 'IRL', 'country_num_code' => 372, 'language_code' => 'en']);
            Countries::create(['name' => 'Israel', 'country_code' => 'ISR', 'country_num_code' => 376, 'language_code' => 'he']);
            Countries::create(['name' => 'Italy', 'country_code' => 'ITA', 'country_num_code' => 380, 'language_code' => 'it']);
            Countries::create(['name' => 'Jamaica', 'country_code' => 'JAM', 'country_num_code' => 388, 'language_code' => 'en']);
            Countries::create(['name' => 'Japan', 'country_code' => 'JPN', 'country_num_code' => 392, 'language_code' => 'ja']);
            Countries::create(['name' => 'Jordan', 'country_code' => 'JOR', 'country_num_code' => 400, 'language_code' => 'ar']);
            Countries::create(['name' => 'Kazakhstan', 'country_code' => 'KAZ', 'country_num_code' => 398, 'language_code' => 'kk']);
            Countries::create(['name' => 'Kenya', 'country_code' => 'KEN', 'country_num_code' => 404, 'language_code' => 'sw']);
            Countries::create(['name' => 'Kiribati', 'country_code' => 'KIR', 'country_num_code' => 296, 'language_code' => 'en']);
            Countries::create(['name' => 'Kuwait', 'country_code' => 'KWT', 'country_num_code' => 414, 'language_code' => 'ar']);
            Countries::create(['name' => 'Kyrgyzstan', 'country_code' => 'KGZ', 'country_num_code' => 417, 'language_code' => 'ky']);
            Countries::create(['name' => 'Lao Peoples Democratic Republic', 'country_code' => 'LAO', 'country_num_code' => 418, 'language_code' => 'lo']);
            Countries::create(['name' => 'Latvia', 'country_code' => 'LVA', 'country_num_code' => 428, 'language_code' => 'lv']);
            Countries::create(['name' => 'Lebanon', 'country_code' => 'LBN', 'country_num_code' => 422, 'language_code' => 'ar']);
            Countries::create(['name' => 'Lesotho', 'country_code' => 'LSO', 'country_num_code' => 426, 'language_code' => 'en']);
            Countries::create(['name' => 'Liberia', 'country_code' => 'LBR', 'country_num_code' => 430, 'language_code' => 'en']);
            Countries::create(['name' => 'Libya', 'country_code' => 'LBY', 'country_num_code' => 434, 'language_code' => 'ar']);
            Countries::create(['name' => 'Liechtenstein', 'country_code' => 'LIE', 'country_num_code' => 438, 'language_code' => 'de']);
            Countries::create(['name' => 'Lithuania', 'country_code' => 'LTU', 'country_num_code' => 440, 'language_code' => 'lt']);
            Countries::create(['name' => 'Luxembourg', 'country_code' => 'LUX', 'country_num_code' => 442, 'language_code' => 'lb']);
            Countries::create(['name' => 'Madagascar', 'country_code' => 'MDG', 'country_num_code' => 450, 'language_code' => 'mg']);
            Countries::create(['name' => 'Malawi', 'country_code' => 'MWI', 'country_num_code' => 454, 'language_code' => 'en']);
            Countries::create(['name' => 'Malaysia', 'country_code' => 'MYS', 'country_num_code' => 458, 'language_code' => 'ms']);
            Countries::create(['name' => 'Maldives', 'country_code' => 'MDV', 'country_num_code' => 462, 'language_code' => 'dv']);
            Countries::create(['name' => 'Mali', 'country_code' => 'MLI', 'country_num_code' => 466, 'language_code' => 'fr']);
            Countries::create(['name' => 'Malta', 'country_code' => 'MLT', 'country_num_code' => 470, 'language_code' => 'mt']);
            Countries::create(['name' => 'Marshall Islands', 'country_code' => 'MHL', 'country_num_code' => 584, 'language_code' => 'en']);
            Countries::create(['name' => 'Mauritania', 'country_code' => 'MRT', 'country_num_code' => 478, 'language_code' => 'ar']);
            Countries::create(['name' => 'Mauritius', 'country_code' => 'MUS', 'country_num_code' => 480, 'language_code' => 'fr']);
            Countries::create(['name' => 'Mexico', 'country_code' => 'MEX', 'country_num_code' => 484, 'language_code' => 'es']);
            Countries::create(['name' => 'Micronesia', 'country_code' => 'FSM', 'country_num_code' => 	583, 'language_code' => 'en']);
            Countries::create(['name' => 'Moldova', 'country_code' => 'MDA', 'country_num_code' => 498, 'language_code' => 'ro']);
            Countries::create(['name' => 'Monaco', 'country_code' => 'MCO', 'country_num_code' => 492, 'language_code' => 'fr']);
            Countries::create(['name' => 'Mongolia', 'country_code' => 'MNG', 'country_num_code' => 496, 'language_code' => 'mn']);
            Countries::create(['name' => 'Montenegro', 'country_code' => 'MNE', 'country_num_code' => 499, 'language_code' => 'sr']);
            Countries::create(['name' => 'Morocco', 'country_code' => 'MAR', 'country_num_code' => 504, 'language_code' => 'fr']);
            Countries::create(['name' => 'Mozambique', 'country_code' => 'MOZ', 'country_num_code' => 508, 'language_code' => 'pt']);
            Countries::create(['name' => 'Myanmar', 'country_code' => 'MMR', 'country_num_code' => 104, 'language_code' => 'my']);
            Countries::create(['name' => 'Namibia', 'country_code' => 'NAM', 'country_num_code' => 516, 'language_code' => 'en']);
            Countries::create(['name' => 'Nauru', 'country_code' => 'NRU', 'country_num_code' => 520, 'language_code' => 'na']);
            Countries::create(['name' => 'Nepal', 'country_code' => 'NPL', 'country_num_code' => 524, 'language_code' => 'ne']);
            Countries::create(['name' => 'Netherlands', 'country_code' => 'NLD', 'country_num_code' => 528, 'language_code' => 'nl']);
            Countries::create(['name' => 'New Zealand', 'country_code' => 'NZL', 'country_num_code' => 554, 'language_code' => 'mi']);
            Countries::create(['name' => 'Nicaragua', 'country_code' => 'NIC', 'country_num_code' => 558, 'language_code' => 'es']);
            Countries::create(['name' => 'Niger', 'country_code' => 'NER', 'country_num_code' => 562, 'language_code' => 'fr']);
            Countries::create(['name' => 'Nigeria', 'country_code' => 'NGA', 'country_num_code' => 566, 'language_code' => 'en']);
            Countries::create(['name' => 'North Korea', 'country_code' => 'PRK', 'country_num_code' => 850, 'language_code' => 'ko']);
            Countries::create(['name' => 'North Macedonia', 'country_code' => 'MKD', 'country_num_code' => 807, 'language_code' => 'mk']);
            Countries::create(['name' => 'Norway', 'country_code' => 'NOR', 'country_num_code' => 578, 'language_code' => 'nb']);
            Countries::create(['name' => 'Oman', 'country_code' => 'OMN', 'country_num_code' => 512, 'language_code' => 'ar']);
            Countries::create(['name' => 'Pakistan', 'country_code' => 'PAK', 'country_num_code' => 586, 'language_code' => 'en']);
            Countries::create(['name' => 'Palau', 'country_code' => 'PLW', 'country_num_code' => 585, 'language_code' => 'en']);
            Countries::create(['name' => 'Panama', 'country_code' => 'PAN', 'country_num_code' => 591, 'language_code' => 'es']);
            Countries::create(['name' => 'Papua New Guinea', 'country_code' => 'PNG', 'country_num_code' => 598, 'language_code' => 'en']);
            Countries::create(['name' => 'Paraguay', 'country_code' => 'PRY', 'country_num_code' => 600, 'language_code' => 'es']);
            Countries::create(['name' => 'Peru', 'country_code' => 'PER', 'country_num_code' => 604, 'language_code' => 'es']);
            Countries::create(['name' => 'Philippines', 'country_code' => 'PHL', 'country_num_code' => 608, 'language_code' => 'en']);
            Countries::create(['name' => 'Poland', 'country_code' => 'POL', 'country_num_code' => 616, 'language_code' => 'pl']);
            Countries::create(['name' => 'Portugal', 'country_code' => 'PRT', 'country_num_code' => 620, 'language_code' => 'pt']);
            Countries::create(['name' => 'Qatar', 'country_code' => 'QAT', 'country_num_code' => 634, 'language_code' => 'ar']);
            Countries::create(['name' => 'Romania', 'country_code' => 'ROU', 'country_num_code' => 642, 'language_code' => 'ro']);
            Countries::create(['name' => 'Russian', 'country_code' => 'RUS', 'country_num_code' => 643, 'language_code' => 'ru']);
            Countries::create(['name' => 'Rwanda', 'country_code' => 'RWA', 'country_num_code' => 646, 'language_code' => 'rw']);
            Countries::create(['name' => 'Saint Kitts and Nevis', 'country_code' => 'KNA', 'country_num_code' => 659, 'language_code' => 'en']);
            Countries::create(['name' => 'Saint Lucia', 'country_code' => 'LCA', 'country_num_code' => 662, 'language_code' => 'en']);
            Countries::create(['name' => 'Samoa', 'country_code' => 'WSM', 'country_num_code' => 882, 'language_code' => 'sm']);
            Countries::create(['name' => 'San Marino', 'country_code' => 'SMR', 'country_num_code' => 674, 'language_code' => 'it']);
            Countries::create(['name' => 'Sao Tome and Principe', 'country_code' => 'STP', 'country_num_code' => 678, 'language_code' => 'pt']);
            Countries::create(['name' => 'Saudi Arabia', 'country_code' => 'SAU', 'country_num_code' => 682, 'language_code' => 'ar']);
            Countries::create(['name' => 'Senegal', 'country_code' => 'SEN', 'country_num_code' => 686, 'language_code' => 'fr']);
            Countries::create(['name' => 'Serbia', 'country_code' => 'SRB', 'country_num_code' => 688, 'language_code' => 'sr']);
            Countries::create(['name' => 'Seychelles', 'country_code' => 'SYC', 'country_num_code' => 690, 'language_code' => 'fr']);
            Countries::create(['name' => 'Sierra Leone', 'country_code' => 'SLE', 'country_num_code' => 694, 'language_code' => 'en']);
            Countries::create(['name' => 'Singapore', 'country_code' => 'SGP', 'country_num_code' => 702, 'language_code' => 'zh']);
            Countries::create(['name' => 'Slovakia', 'country_code' => 'SVK', 'country_num_code' => 703, 'language_code' => 'sk']);
            Countries::create(['name' => 'Slovenia', 'country_code' => 'SVN', 'country_num_code' => 705, 'language_code' => 'sl']);
            Countries::create(['name' => 'Solomon Islands', 'country_code' => 'SLB', 'country_num_code' => 90, 'language_code' => 'en']);
            Countries::create(['name' => 'Somalia', 'country_code' => 'SOM', 'country_num_code' => 706, 'language_code' => 'so']);
            Countries::create(['name' => 'South Africa', 'country_code' => 'ZAF', 'country_num_code' => 710, 'language_code' => 'en']);
            Countries::create(['name' => 'South Korea', 'country_code' => 'KOR', 'country_num_code' => 82, 'language_code' => 'ko']);
            Countries::create(['name' => 'South Sudan', 'country_code' => 'SSD', 'country_num_code' => 728, 'language_code' => 'en']);
            Countries::create(['name' => 'Spain', 'country_code' => 'ESP', 'country_num_code' => 724, 'language_code' => 'ca']);
            Countries::create(['name' => 'Sri Lanka', 'country_code' => 'LKA', 'country_num_code' => 144, 'language_code' => 'si']);
            Countries::create(['name' => 'St. Vincent & Grenadines', 'country_code' => 'VCT	', 'country_num_code' => 670, 'language_code' => 'en']);
            Countries::create(['name' => 'State of Palestine', 'country_code' => 'PSE', 'country_num_code' => 275, 'language_code' => 'ar']);
            Countries::create(['name' => 'Sudan', 'country_code' => 'SDN', 'country_num_code' => 729, 'language_code' => 'ar']);
            Countries::create(['name' => 'Suriname', 'country_code' => 'SUR', 'country_num_code' => 740, 'language_code' => 'nl']);
            Countries::create(['name' => 'Sweden', 'country_code' => 'SWE', 'country_num_code' => 752, 'language_code' => 'sv']);
            Countries::create(['name' => 'Switzerland', 'country_code' => 'CHE', 'country_num_code' => 756, 'language_code' => 'de']);
            Countries::create(['name' => 'Syrian Arab Republic', 'country_code' => 'SYR', 'country_num_code' => 760, 'language_code' => 'ar']);
            Countries::create(['name' => 'Tajikistan', 'country_code' => 'TJK', 'country_num_code' => 762, 'language_code' => 'tg']);
            Countries::create(['name' => 'Tanzania', 'country_code' => 'TZA', 'country_num_code' => 834, 'language_code' => 'sw']);
            Countries::create(['name' => 'Thailand', 'country_code' => 'THA', 'country_num_code' => 764, 'language_code' => 'th']);
            Countries::create(['name' => 'Timor-Leste', 'country_code' => 'TLS', 'country_num_code' => 626, 'language_code' => 'pt']);
            Countries::create(['name' => 'Togo', 'country_code' => 'TGO', 'country_num_code' => 768, 'language_code' => 'fr']);
            Countries::create(['name' => 'Tonga', 'country_code' => 'TON', 'country_num_code' => 776, 'language_code' => 'en']);
            Countries::create(['name' => 'Trinidad and Tobago', 'country_code' => 'TTO', 'country_num_code' => 780, 'language_code' => 'en']);
            Countries::create(['name' => 'Tunisia', 'country_code' => 'TUN', 'country_num_code' => 788, 'language_code' => 'ar']);
            Countries::create(['name' => 'Turkey', 'country_code' => 'TUR', 'country_num_code' => 792, 'language_code' => 'tr']);
            Countries::create(['name' => 'Turkmenistan', 'country_code' => 'TKM', 'country_num_code' => 795, 'language_code' => 'tk']);
            Countries::create(['name' => 'Tuvalu', 'country_code' => 'TUV', 'country_num_code' => 798, 'language_code' => 'en']);
            Countries::create(['name' => 'Uganda', 'country_code' => 'UGA', 'country_num_code' => 800, 'language_code' => 'en']);
            Countries::create(['name' => 'Ukraine', 'country_code' => 'UKR', 'country_num_code' => 804, 'language_code' => 'uk']);
            Countries::create(['name' => 'United Arab Emirates', 'country_code' => 'ARE', 'country_num_code' => 784, 'language_code' => 'ar']);
            Countries::create(['name' => 'United Kingdom of Great Britain and Northern Ireland', 'country_code' => 'GBR', 'country_num_code' => 826, 'language_code' => 'en']);
            Countries::create(['name' => 'United States of America', 'country_code' => 'USA', 'country_num_code' => 840, 'language_code' => 'en']);
            Countries::create(['name' => 'Uruguay', 'country_code' => 'URY', 'country_num_code' => 858, 'language_code' => 'es']);
            Countries::create(['name' => 'Uzbekistan', 'country_code' => 'UZB', 'country_num_code' => 860, 'language_code' => 'uz']);
            Countries::create(['name' => 'Vanuatu', 'country_code' => 'VUT', 'country_num_code' => 548, 'language_code' => 'bi']);
            Countries::create(['name' => 'Venezuela', 'country_code' => 'VEN', 'country_num_code' => 862, 'language_code' => 'es']);
            Countries::create(['name' => 'Vietnam', 'country_code' => 'VNM', 'country_num_code' => 704, 'language_code' => 'vi']);
            Countries::create(['name' => 'Yemen', 'country_code' => 'YEM', 'country_num_code' => 887, 'language_code' => 'ar']);
            Countries::create(['name' => 'Zambia', 'country_code' => 'ZMB', 'country_num_code' => 894, 'language_code' => 'en']);
            Countries::create(['name' => 'Zimbabwe', 'country_code' => 'ZWE', 'country_num_code' => 716, 'language_code' => 'en']);
        } else {
            echo "Qtde: " . $count . " Records Inside Database!";
        }
    }
}
