version: '3'
services:

    nginx:
        build:
            context: "./docker/nginx"
        depends_on:
            - php-fpm
        volumes:
            - ${NGINX_SSL_PATH}:/etc/nginx/ssl
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        ports:
            - "${NGINX_HOST_HTTPS_PORT}:443"
            - "${NGINX_HOST_HTTP_PORT}:80"
        networks:
            sail:
                ipv4_address: 172.22.0.3

    php-fpm:
        build:
            context: "./docker/php-fpm"
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        networks:
            sail:
                ipv4_address: 172.22.0.4
        expose:
            - "9000"

    laravel-horizon:
        build:
            context: ./docker/laravel-horizon
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
            - ./docker/laravel-horizon/supervisord.d:/etc/supervisord.d
        depends_on:
            - php-fpm
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
        networks:
            sail:
                ipv4_address: 172.22.0.5

networks:
    sail:
        driver: bridge
        ipam:
            config:
                - subnet: 172.22.0.0/24

